# permalinks
permalink: /:year-:month-:day/:title

# setup
title: Engineering & Coffee
paginate: 5
baseurl: ""
url: "https://kohi.uk"
remote_theme: "mmistakes/minimal-mistakes@4.16.6"

# assets
sass:
  sass_dir: _sass
  style: :compressed

# about
author:
  name: Rob Beal
  url: https://kohi.uk

# gems
gems:
  - jekyll-paginate
  - jekyll-include-cache
